---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
linkGit1="https://github.com/Fundamentals-Sarah/HW3-Attempt3/raw/refs/heads/main/Maternalmortalityratio.csv"
```
```{r}
matmort=rio::import(file = linkGit1)
```

```{r}
str(matmort)
```

```{r}
head(matmort)
```
```{r}
tail(matmort)
```
```{r}
names(matmort)
```


```{r}
names(matmort)[names(matmort)!='region']
```

```{r}
matmort_subset <- matmort[, c(1,3,6)]
names(matmort_subset)[3]<- "Region"
names(matmort_subset)[2]<- "Maternal_Death_Rate"
names(matmort_subset)[1]<- "Country_Name"
```
```{r}
str(matmort_subset)
```

```{r}
matmort_subset$Country_Name[grep("[^a-zA-Z\\s]",matmort_subset$Country_Name,perl = T)]
```

```{r}
matmort_subset$Maternal_Death_Rate[grep("\\D",matmort_subset$Maternal_Death_Rate)]
```

```{r}
table(matmort_subset$Region)
```

```{r}
sapply(strsplit(matmort_subset$Country_Name, split = '(', fixed = TRUE), `[`, 1)
```

```{r}
matmort_subset$Country_Name <- sapply(strsplit(matmort_subset$Country_Name, split = '(', fixed = TRUE), `[`, 1)
```

```{r}
matmort_subset
```

```{r}
matmort_subset$Country_Name <- trimws(matmort_subset$Country_Name)
matmort_subset$Country_Name == trimws(matmort_subset$Country_Name)
matmort_subset$Region <- trimws(matmort_subset$Region)
matmort_subset$Region == trimws(matmort_subset$Region)
```

```{r}
saveRDS(matmort_subset,"matmortality.RDS")
```

```{r}
matmortalityRDS=readRDS("matmortality.RDS")
str(matmortalityRDS)
```

```{r}
write.csv(matmort_subset,"maternal_cleaned.csv", row.names=FALSE)
maternalcleanedCSV=read.csv("maternal_cleaned.csv")
str(maternalcleanedCSV)
```






